const cities = [
  { label: "Mumbai, Maharashtra", value: "Mumbai" },
  { label: "Delhi, Delhi", value: "Delhi" },
  { label: "Bangalore, Karnataka", value: "Bangalore" },
  { label: "Hyderabad, Telangana", value: "Hyderabad" },
  { label: "Ahmedabad, Gujarat", value: "Ahmedabad" },
  { label: "Chennai, Tamil Nadu", value: "Chennai" },
  { label: "Kolkata, West Bengal", value: "Kolkata" },
  { label: "Pune, Maharashtra", value: "Pune" },
  { label: "Jaipur, Rajasthan", value: "Jaipur" },
  { label: "Surat, Gujarat", value: "Surat" },
  { label: "Lucknow, Uttar Pradesh", value: "Lucknow" },
  { label: "Kanpur, Uttar Pradesh", value: "Kanpur" },
  { label: "Nagpur, Maharashtra", value: "Nagpur" },
  { label: "Indore, Madhya Pradesh", value: "Indore" },
  { label: "Thane, Maharashtra", value: "Thane" },
  { label: "Bhopal, Madhya Pradesh", value: "Bhopal" },
  { label: "Visakhapatnam, Andhra Pradesh", value: "Visakhapatnam" },
  { label: "Pimpri-Chinchwad, Maharashtra", value: "Pimpri-Chinchwad" },
  { label: "Patna, Bihar", value: "Patna" },
  { label: "Vadodara, Gujarat", value: "Vadodara" },
  { label: "Ludhiana, Punjab", value: "Ludhiana" },
  { label: "Agra, Uttar Pradesh", value: "Agra" },
  { label: "Nashik, Maharashtra", value: "Nashik" },
  { label: "Faridabad, Haryana", value: "Faridabad" },
  { label: "Meerut, Uttar Pradesh", value: "Meerut" },
  { label: "Rajkot, Gujarat", value: "Rajkot" },
  { label: "Kalyan-Dombivli, Maharashtra", value: "Kalyan-Dombivli" },
  { label: "Vasai-Virar, Maharashtra", value: "Vasai-Virar" },
  { label: "Varanasi, Uttar Pradesh", value: "Varanasi" },
  { label: "Srinagar, Jammu and Kashmir", value: "Srinagar" },
  { label: "Aurangabad, Maharashtra", value: "Aurangabad" },
  { label: "Dhanbad, Jharkhand", value: "Dhanbad" },
  { label: "Amritsar, Punjab", value: "Amritsar" },
  { label: "Navi Mumbai, Maharashtra", value: "Navi Mumbai" },
  { label: "Allahabad, Uttar Pradesh", value: "Allahabad" },
  { label: "Howrah, West Bengal", value: "Howrah" },
  { label: "Ranchi, Jharkhand", value: "Ranchi" },
  { label: "Gwalior, Madhya Pradesh", value: "Gwalior" },
  { label: "Jabalpur, Madhya Pradesh", value: "Jabalpur" },
  { label: "Coimbatore, Tamil Nadu", value: "Coimbatore" },
  { label: "Vijayawada, Andhra Pradesh", value: "Vijayawada" },
  { label: "Madurai, Tamil Nadu", value: "Madurai" },
  { label: "Guwahati, Assam", value: "Guwahati" },
  { label: "Chandrapur, Maharashtra", value: "Chandrapur" },
  { label: "Hubballi-Dharwad, Karnataka", value: "Hubballi-Dharwad" },
  { label: "Amravati, Maharashtra", value: "Amravati" },
  { label: "Moradabad, Uttar Pradesh", value: "Moradabad" },
  { label: "Gurgaon, Haryana", value: "Gurgaon" },
  { label: "Aligarh, Uttar Pradesh", value: "Aligarh" },
  { label: "Jalandhar, Punjab", value: "Jalandhar" },
  { label: "Tiruchirappalli, Tamil Nadu", value: "Tiruchirappalli" },
  { label: "Bhubaneswar, Odisha", value: "Bhubaneswar" },
  { label: "Salem, Tamil Nadu", value: "Salem" },
  { label: "Warangal, Telangana", value: "Warangal" },
  { label: "Mira-Bhayandar, Maharashtra", value: "Mira-Bhayandar" },
  { label: "Thiruvananthapuram, Kerala", value: "Thiruvananthapuram" },
  { label: "Bhiwandi, Maharashtra", value: "Bhiwandi" },
  { label: "Saharanpur, Uttar Pradesh", value: "Saharanpur" },
  { label: "Guntur, Andhra Pradesh", value: "Guntur" },
  { label: "Amravati, Andhra Pradesh", value: "Amravati" },
  { label: "Jalgaon, Maharashtra", value: "Jalgaon" },
  { label: "Gulbarga, Karnataka", value: "Gulbarga" },
  { label: "Bikaner, Rajasthan", value: "Bikaner" },
  { label: "Noida, Uttar Pradesh", value: "Noida" },
  { label: "Jamshedpur, Jharkhand", value: "Jamshedpur" },
  { label: "Ujjain, Madhya Pradesh", value: "Ujjain" },
  { label: "Loni, Uttar Pradesh", value: "Loni" },
  { label: "Siliguri, West Bengal", value: "Siliguri" },
  { label: "Jhansi, Uttar Pradesh", value: "Jhansi" },
  { label: "Ulhasnagar, Maharashtra", value: "Ulhasnagar" },
  { label: "Nellore, Andhra Pradesh", value: "Nellore" },
  { label: "Jammu, Jammu and Kashmir", value: "Jammu" },
  { label: "Sangli, Maharashtra", value: "Sangli" },
  { label: "Mangalore, Karnataka", value: "Mangalore" },
  { label: "Erode, Tamil Nadu", value: "Erode" },
  { label: "Belgaum, Karnataka", value: "Belgaum" },
  { label: "Ambattur, Tamil Nadu", value: "Ambattur" },
  { label: "Tirunelveli, Tamil Nadu", value: "Tirunelveli" },
  { label: "Malegaon, Maharashtra", value: "Malegaon" },
  { label: "Gaya, Bihar", value: "Gaya" },
  { label: "Tiruppur, Tamil Nadu", value: "Tiruppur" },
  { label: "Davanagere, Karnataka", value: "Davanagere" },
  { label: "Kozhikode, Kerala", value: "Kozhikode" },
  { label: "Akola, Maharashtra", value: "Akola" },
  { label: "Kurnool, Andhra Pradesh", value: "Kurnool" },
  { label: "Bokaro Steel City, Jharkhand", value: "Bokaro Steel City" },
  { label: "Rajpur Sonarpur, West Bengal", value: "Rajpur Sonarpur" },
  { label: "Rajahmundry, Andhra Pradesh", value: "Rajahmundry" },
  { label: "Ballari, Karnataka", value: "Ballari" },
  { label: "Agartala, Tripura", value: "Agartala" },
  { label: "Bhagalpur, Bihar", value: "Bhagalpur" },
  { label: "Latur, Maharashtra", value: "Latur" },
  { label: "Dhule, Maharashtra", value: "Dhule" },
  { label: "Korba, Chhattisgarh", value: "Korba" },
  { label: "Bhilwara, Rajasthan", value: "Bhilwara" },
  { label: "Brahmapur, Odisha", value: "Brahmapur" },
  { label: "Muzaffarpur, Bihar", value: "Muzaffarpur" },
  { label: "Ahmednagar, Maharashtra", value: "Ahmednagar" },
  { label: "Mathura, Uttar Pradesh", value: "Mathura" },
  { label: "Kollam, Kerala", value: "Kollam" },
  { label: "Avadi, Tamil Nadu", value: "Avadi" },
  { label: "Kadapa, Andhra Pradesh", value: "Kadapa" },
  { label: "Kamarhati, West Bengal", value: "Kamarhati" },
  { label: "Sambalpur, Odisha", value: "Sambalpur" },
  { label: "Bilaspur, Chhattisgarh", value: "Bilaspur" },
  { label: "Shahjahanpur, Uttar Pradesh", value: "Shahjahanpur" },
  { label: "Satara, Maharashtra", value: "Satara" },
  { label: "Bijapur, Karnataka", value: "Bijapur" },
  { label: "Kakinada, Andhra Pradesh", value: "Kakinada" },
  { label: "Rampur, Uttar Pradesh", value: "Rampur" },
  { label: "Shimoga, Karnataka", value: "Shimoga" },
  { label: "Chandrapur, Maharashtra", value: "Chandrapur" },
  { label: "Junagadh, Gujarat", value: "Junagadh" },
  { label: "Thrissur, Kerala", value: "Thrissur" },
  { label: "Alwar, Rajasthan", value: "Alwar" },
  { label: "Bardhaman, West Bengal", value: "Bardhaman" },
  { label: "Kulti, West Bengal", value: "Kulti" },
  { label: "Nizamabad, Telangana", value: "Nizamabad" },
  { label: "Parbhani, Maharashtra", value: "Parbhani" },
  { label: "Tumkur, Karnataka", value: "Tumkur" },
  { label: "Khammam, Telangana", value: "Khammam" },
  { label: "Ozhukarai, Puducherry", value: "Ozhukarai" },
  { label: "Bihar Sharif, Bihar", value: "Bihar Sharif" },
  { label: "Panipat, Haryana", value: "Panipat" },
  { label: "Darbhanga, Bihar", value: "Darbhanga" },
  { label: "Bally, West Bengal", value: "Bally" },
  { label: "Aizawl, Mizoram", value: "Aizawl" },
  { label: "Dewas, Madhya Pradesh", value: "Dewas" },
  { label: "Ichalkaranji, Maharashtra", value: "Ichalkaranji" },
  { label: "Karnal, Haryana", value: "Karnal" },
  { label: "Bathinda, Punjab", value: "Bathinda" },
  { label: "Jalna, Maharashtra", value: "Jalna" },
  { label: "Eluru, Andhra Pradesh", value: "Eluru" },
  { label: "Barasat, West Bengal", value: "Barasat" },
  { label: "Kirari Suleman Nagar, Delhi", value: "Kirari Suleman Nagar" },
  { label: "Purnia, Bihar", value: "Purnia" },
  { label: "Satna, Madhya Pradesh", value: "Satna" },
  { label: "Mau, Uttar Pradesh", value: "Mau" },
  { label: "Sonipat, Haryana", value: "Sonipat" },
  { label: "Farrukhabad, Uttar Pradesh", value: "Farrukhabad" },
  { label: "Sagar, Madhya Pradesh", value: "Sagar" },
  { label: "Rourkela, Odisha", value: "Rourkela" },
  { label: "Durg, Chhattisgarh", value: "Durg" },
  { label: "Imphal, Manipur", value: "Imphal" },
  { label: "Ratlam, Madhya Pradesh", value: "Ratlam" },
  { label: "Hapur, Uttar Pradesh", value: "Hapur" },
  { label: "Anantapur, Andhra Pradesh", value: "Anantapur" },
  { label: "Arrah, Bihar", value: "Arrah" },
  { label: "Karimnagar, Telangana", value: "Karimnagar" },
  { label: "Etawah, Uttar Pradesh", value: "Etawah" },
  { label: "Ambernath, Maharashtra", value: "Ambernath" },
  { label: "North Dumdum, West Bengal", value: "North Dumdum" },
  { label: "Bharatpur, Rajasthan", value: "Bharatpur" },
  { label: "Begusarai, Bihar", value: "Begusarai" },
  { label: "New Delhi, Delhi", value: "New Delhi" },
  { label: "Kanpur, Uttar Pradesh", value: "Kanpur" },
  { label: "Lucknow, Uttar Pradesh", value: "Lucknow" },
  { label: "Varanasi, Uttar Pradesh", value: "Varanasi" },
  { label: "Allahabad, Uttar Pradesh", value: "Allahabad" },
  { label: "Moradabad, Uttar Pradesh", value: "Moradabad" },
  { label: "Aligarh, Uttar Pradesh", value: "Aligarh" },
  { label: "Agra, Uttar Pradesh", value: "Agra" },
  { label: "Bareilly, Uttar Pradesh", value: "Bareilly" },
  { label: "Gorakhpur, Uttar Pradesh", value: "Gorakhpur" },
  { label: "Saharanpur, Uttar Pradesh", value: "Saharanpur" },
  { label: "Noida, Uttar Pradesh", value: "Noida" },
  { label: "Firozabad, Uttar Pradesh", value: "Firozabad" },
  { label: "Jhansi, Uttar Pradesh", value: "Jhansi" },
  { label: "Muzaffarnagar, Uttar Pradesh", value: "Muzaffarnagar" },
  { label: "Mathura, Uttar Pradesh", value: "Mathura" },
  { label: "Shahjahanpur, Uttar Pradesh", value: "Shahjahanpur" },
  { label: "Bulandshahr, Uttar Pradesh", value: "Bulandshahr" },
  { label: "Rampur, Uttar Pradesh", value: "Rampur" },
  { label: "Hapur, Uttar Pradesh", value: "Hapur" },
  { label: "Mau, Uttar Pradesh", value: "Mau" },
  { label: "Farrukhabad, Uttar Pradesh", value: "Farrukhabad" },
  { label: "Faizabad, Uttar Pradesh", value: "Faizabad" },
  { label: "Etawah, Uttar Pradesh", value: "Etawah" },
  { label: "Sitapur, Uttar Pradesh", value: "Sitapur" },
  { label: "Sambhal, Uttar Pradesh", value: "Sambhal" },
  { label: "Hardoi, Uttar Pradesh", value: "Hardoi" },
  { label: "Lakhimpur, Uttar Pradesh", value: "Lakhimpur" },
  { label: "Rae Bareli, Uttar Pradesh", value: "Rae Bareli" },
  { label: "Orai, Uttar Pradesh", value: "Orai" },
  { label: "Unnao, Uttar Pradesh", value: "Unnao" },
  { label: "Lalitpur, Uttar Pradesh", value: "Lalitpur" },
  { label: "Deoria, Uttar Pradesh", value: "Deoria" },
  { label: "Machhlishahr, Uttar Pradesh", value: "Machhlishahr" },
  { label: "Banda, Uttar Pradesh", value: "Banda" },
  { label: "Pilibhit, Uttar Pradesh", value: "Pilibhit" },
  { label: "Amroha, Uttar Pradesh", value: "Amroha" },
  { label: "Bahraich, Uttar Pradesh", value: "Bahraich" },
  { label: "Basti, Uttar Pradesh", value: "Basti" },
  { label: "Chandausi, Uttar Pradesh", value: "Chandausi" },
  { label: "Nagina, Uttar Pradesh", value: "Nagina" },
  { label: "Barabanki, Uttar Pradesh", value: "Barabanki" },
  { label: "Tanda, Uttar Pradesh", value: "Tanda" },
  { label: "Sultanpur, Uttar Pradesh", value: "Sultanpur" },
  { label: "Mirzapur, Uttar Pradesh", value: "Mirzapur" },
  { label: "Bareilly, Uttar Pradesh", value: "Bareilly" },
  { label: "Rath, Uttar Pradesh", value: "Rath" },
  { label: "Lakhnau, Uttar Pradesh", value: "Lakhnau" },
  { label: "Jhansi, Uttar Pradesh", value: "Jhansi" },
];
module.exports = cities;
